[DEV-1982] Pre-Sale
ovnstable/ovnstable-core pull request #246
Opened 2023-09-06 11:29 UTC by venikpapa

2023-09-06 12:10 UTC, Vorh commented on pkg/pre-sale/contracts/OverflowICO.sol
>          emissionToken.safeTransferFrom(msg.sender, address(this), totalEmission);
emissionToken заменить на salesToken, иначе путаницы возникает. 
Т.к. в методе commit уже используется salesToken в качестве токена, который пользователь стейкает.

salesToken - OVN
commitToken - USD+ 

Можно ввести такое наименование.

2023-09-06 12:27 UTC, Vorh commented
Тесты есть, но в них не хватает ключевого: проверки итогового результата.
Сейчас в них происходит вызов методов, но не проверяются итоговые значения: балансы пользователей, рейты и т.д. 

Без проверки значений теряется смысл самих тестов.

2023-09-07 14:27 UTC, 4yuka requested changes

2023-09-07 14:27 UTC, 4yuka commented on pkg/pre-sale/contracts/OverflowICO.sol
> +        _updateTime();
Если этот вызов никак не влияет на проверки, то нужно его поставить после них

2023-09-07 14:27 UTC, 4yuka commented on pkg/pre-sale/contracts/OverflowICO.sol
> +        commitToken.safeTransferFrom(msg.sender, address(this), amount);
Если этот вызов никак не влияет на проверки, то нужно его поставить после них

2023-09-07 14:27 UTC, 4yuka commented on pkg/pre-sale/contracts/OverflowICO.sol
>              started && block.timestamp >= startTime && block.timestamp < endTime,
Как будто бы дублирующаяся проверка в getUserState

2023-09-07 14:27 UTC, 4yuka commented on pkg/pre-sale/contracts/OverflowICO.sol
> +        require(block.timestamp > endTime, "Can only claim tokens after the sale has ended.");
Дублирующаяся проверка в getUserState?

2023-09-07 14:27 UTC, 4yuka commented on pkg/pre-sale/contracts/OverflowICO.sol
> +        require(commitments[msg.sender] > 0, "You have not deposited any USD+.");
Дублирующаяся проверка в getUserState?

2023-09-07 14:27 UTC, 4yuka commented on pkg/pre-sale/contracts/OverflowICO.sol
> +        _updateTime();
Нужен вызов до проверок?

2023-09-07 14:27 UTC, 4yuka commented on pkg/pre-sale/contracts/OverflowICO.sol
> +    function finish() public onlyOwner {
Вызывается внутри метода claimRefund. Мы будем вызывать также его извне?

2023-09-07 14:27 UTC, 4yuka commented on pkg/pre-sale/contracts/OverflowICO.sol
> +        require(block.timestamp >= claimBonusTime, "not bonus yet");
Дублирующаяся проверка в getUserState?

2023-09-07 14:27 UTC, 4yuka commented on pkg/pre-sale/contracts/OverflowICO.sol
> +        require(block.timestamp >= vestingBeginTime, "not claimVesting yet");
Дублирующаяся проверка в getUserState?

2023-09-07 14:27 UTC, 4yuka commented on pkg/pre-sale/contracts/OverflowICO.sol
> +        require(block.timestamp >= claimSalesFirstPartTime, "not claimSalesFirstPart yet");
Дублирующаяся проверка в getUserState?

2023-09-07 14:27 UTC, 4yuka commented on pkg/pre-sale/contracts/OverflowICO.sol
>      function donate() external payable {
Если функция не нужна, то можно удалить

2023-09-07 14:27 UTC, 4yuka commented on pkg/pre-sale/contracts/OverflowICO.sol
> +        uint256 a2 = finalCommit[msg.sender];
Переименуй переменную в нормальное наименование, чтобы было понятно за что она отвечает

2023-09-07 14:27 UTC, 4yuka commented on pkg/pre-sale/contracts/OverflowICO.sol
> +        uint256 a1 = finalSales[msg.sender];
Переименуй переменную в нормальное наименование, чтобы было понятно за что она отвечает

2023-09-07 14:27 UTC, 4yuka commented on pkg/pre-sale/contracts/OverflowICO.sol
>              uint256 amt = commitments[msg.sender];
Переименуй переменную в нормальное наименование, чтобы было понятно за что она отвечает

2023-09-07 14:27 UTC, 4yuka commented on pkg/pre-sale/contracts/OverflowICO.sol
> +            timeRatio += share * 1e18 / totalCommitments;
Вынести все захардкоженные значения в переменные, либо если это decimals, то использовать его

2023-09-07 14:27 UTC, 4yuka commented on pkg/pre-sale/contracts/OverflowICO.sol
> +        return value * timeRatio / 1e18;
Вынести все захардкоженные значения в переменные, либо если это decimals, то использовать его

2023-09-07 14:48 UTC, venikpapa commented on pkg/pre-sale/contracts/OverflowICO.sol
>              uint256 amt = commitments[msg.sender];
done

2023-09-07 14:48 UTC, venikpapa commented on pkg/pre-sale/contracts/OverflowICO.sol
> +        uint256 a1 = finalSales[msg.sender];
done

2023-09-07 14:48 UTC, venikpapa commented on pkg/pre-sale/contracts/OverflowICO.sol
> +        uint256 a2 = finalCommit[msg.sender];
done

2023-09-07 14:48 UTC, venikpapa commented on pkg/pre-sale/contracts/OverflowICO.sol
>      function donate() external payable {
done

2023-09-07 14:48 UTC, venikpapa commented on pkg/pre-sale/contracts/OverflowICO.sol
> +        require(block.timestamp >= claimSalesFirstPartTime, "not claimSalesFirstPart yet");
Да, но пофиг, тут словами зато он скажет почему реверт

2023-09-07 14:48 UTC, venikpapa commented on pkg/pre-sale/contracts/OverflowICO.sol
> +        require(block.timestamp >= vestingBeginTime, "not claimVesting yet");
Да, но пофиг, тут словами зато он скажет почему реверт

2023-09-07 14:48 UTC, venikpapa commented on pkg/pre-sale/contracts/OverflowICO.sol
> +        require(block.timestamp >= claimBonusTime, "not bonus yet");
Да, но пофиг, тут словами зато он скажет почему реверт

2023-09-07 14:48 UTC, venikpapa commented on pkg/pre-sale/contracts/OverflowICO.sol
> +    function finish() public onlyOwner {
да, надо оставить возможность самим дернуть, пусть эта возможность будет

2023-09-07 14:48 UTC, venikpapa commented on pkg/pre-sale/contracts/OverflowICO.sol
> +        _updateTime();
done

2023-09-07 14:48 UTC, venikpapa commented on pkg/pre-sale/contracts/OverflowICO.sol
> +        require(commitments[msg.sender] > 0, "You have not deposited any USD+.");
Да, но пофиг, тут словами зато он скажет почему реверт

2023-09-07 14:48 UTC, venikpapa commented on pkg/pre-sale/contracts/OverflowICO.sol
> +        require(block.timestamp > endTime, "Can only claim tokens after the sale has ended.");
Да, но пофиг, тут словами зато он скажет почему реверт

2023-09-07 14:48 UTC, venikpapa commented on pkg/pre-sale/contracts/OverflowICO.sol
>              started && block.timestamp >= startTime && block.timestamp < endTime,
Да, но пофиг, тут словами зато он скажет почему реверт

2023-09-07 14:48 UTC, venikpapa commented on pkg/pre-sale/contracts/OverflowICO.sol
> +        commitToken.safeTransferFrom(msg.sender, address(this), amount);
done

2023-09-07 14:48 UTC, venikpapa commented on pkg/pre-sale/contracts/OverflowICO.sol
> +        _updateTime();
done

2023-09-07 14:48 UTC, venikpapa commented on pkg/pre-sale/contracts/OverflowICO.sol
> +        totalSales = params.totalSales;
мы задаем его в конструкторе, чтобы можно было дернуть старт и автоматом нужная сумма перешла

2023-09-07 14:49 UTC, venikpapa commented on pkg/pre-sale/contracts/OverflowICO.sol
>          require(params.startTime >= block.timestamp, "Start time must be in the future.");
done

2023-09-07 14:49 UTC, venikpapa commented on pkg/pre-sale/contracts/OverflowICO.sol
> -    function calculateEmission(uint256 value) internal view returns (uint256) {
это коммент на код, которого нет)

2023-09-07 14:49 UTC, venikpapa commented on pkg/pre-sale/contracts/OverflowICO.sol
>      struct SetUpParams {
done

2023-09-07 14:49 UTC, venikpapa commented on pkg/pre-sale/contracts/OverflowICO.sol
> +    struct UserInfo {
done

2023-09-07 14:49 UTC, venikpapa commented on pkg/pre-sale/contracts/example/OverflowICOExample.sol
done

2023-09-07 14:49 UTC, venikpapa commented on pkg/pre-sale/contracts/example/LinearVestingExample.sol
done

2023-09-07 14:49 UTC, venikpapa commented on pkg/pre-sale/contracts/test/CommitToken.sol
> +pragma solidity >=0.8.0 <0.9.0;
done

2023-09-07 14:49 UTC, venikpapa commented on pkg/pre-sale/contracts/example/LinearVestingExample.sol
> +// SPDX-License-Identifier: UNLICENSED
done

2023-09-07 14:49 UTC, venikpapa commented on pkg/pre-sale/contracts/test/libraries/WadRayMath.sol
done

2023-09-08 07:31 UTC, 4yuka requested changes

2023-09-08 07:31 UTC, 4yuka commented on pkg/pre-sale/contracts/OverflowICO.sol
> +    function _updateTimeStatic() internal view returns (uint256) {
Нужны тесты на эту функцию. Как минимум граничные проверки, что произойдёт при старте коммитов и что будет на finish.

2023-09-08 07:31 UTC, 4yuka commented on pkg/pre-sale/contracts/OverflowICO.sol
> +                vested = Math.mulDiv(claimableTotal[user], block.timestamp - vestingBeginTime, vestingDuration);
Здесь может быть отрицательное значение, если block.timestamp < vestingBeginTime

2023-09-08 07:31 UTC, 4yuka commented on pkg/pre-sale/contracts/OverflowICO.sol
> +            vested = Math.mulDiv(claimableTotal[addr], block.timestamp - vestingBeginTime, vestingDuration);
Здесь может быть отрицательное значение, если block.timestamp < vestingBeginTime

2023-09-08 07:31 UTC, 4yuka commented on pkg/pre-sale/contracts/OverflowICO.sol
> +        _updateTime();
В функции _updateTime используется переменная totalCommitments, которая ниже изменяется. Ты уверен что надо вызывать эту функцию до инкремента? Что будет при первом и последнем коммите?

2023-09-08 07:31 UTC, 4yuka commented on pkg/pre-sale/contracts/OverflowICO.sol
> +        missedCommit[msg.sender] += _calculateCommit(amount);
Здесь идёт расчёт по timeRatio. Что будет при первом коммите?

2023-09-08 10:15 UTC, venikpapa commented on pkg/pre-sale/contracts/OverflowICO.sol
> +            vested = Math.mulDiv(claimableTotal[addr], block.timestamp - vestingBeginTime, vestingDuration);
done

2023-09-08 10:15 UTC, venikpapa commented on pkg/pre-sale/contracts/OverflowICO.sol
> +                vested = Math.mulDiv(claimableTotal[user], block.timestamp - vestingBeginTime, vestingDuration);
done

2023-09-08 10:15 UTC, venikpapa commented on pkg/pre-sale/contracts/OverflowICO.sol
> +        if (getUserState(user) == UserPresaleState.WAITING_FOR_PRESALE_START) {
done

2023-09-08 10:15 UTC, venikpapa commented on pkg/pre-sale/contracts/Whitelist.sol
> +contract Whitelist is IWhitelist, Initializable, AccessControlUpgradeable, UUPSUpgradeable {
потом

2023-09-08 10:16 UTC, venikpapa commented on pkg/pre-sale/contracts/test/MockWhitelist.sol
> +// SPDX-License-Identifier: UNLICENSED
done

2023-09-08 22:49 UTC, valpaq requested changes

2023-09-08 22:49 UTC, valpaq commented on pkg/pre-sale/contracts/OverflowICO.sol
> +                uint256 commitToBonus = commitToken.balanceOf(address(this)) - totalCommitments;
Если был финиш и овнер забрал токены, то commitToken.balanceOf() будет меньше чем totalCommitments, поэтому тесты не проходят щас с getUserInfo

2023-09-08 22:49 UTC, valpaq commented on pkg/pre-sale/contracts/OverflowICO.sol
> +            finish();
на finish стоит onlyOwner, и если я все правильно понимаю, то транза будет падать по require внутри. Тогда нет смысла ее тут, думаю лучше просто require(!finished, "not finished");

2023-09-08 22:49 UTC, valpaq commented on pkg/pre-sale/contracts/OverflowICO.sol
> +        missedCommit[msg.sender] += _calculateCommit(amount);
0

2023-09-08 22:49 UTC, valpaq commented on pkg/pre-sale/contracts/OverflowICO.sol
> +        totalTime = 1e18;
большое число для точности времени, всегда связано с share и больше никак

2023-09-08 22:49 UTC, valpaq commented on pkg/pre-sale/contracts/OverflowICO.sol
> +                uint256 totalShare = totalCommitments * timeRatioStatic - totalMissedCommit;
в моем тесте в эксельке получилось что totalShare != сумме всех остальных шер, и тогда математика не сходится, если я правильно понимаю. https://docs.google.com/spreadsheets/d/1KCuE-FDgzeTcx7idCBOOPlYZ_SigvXu5mUAWrwHfaSM/edit?usp=sharing вот тут есть все действия по листам и результаты

2023-09-08 23:09 UTC, venikpapa commented on pkg/pre-sale/contracts/OverflowICO.sol
> +                uint256 commitToBonus = commitToken.balanceOf(address(this)) - totalCommitments;
Да, это я как раз щас нашел и поправил это место

2023-09-08 23:11 UTC, venikpapa commented on pkg/pre-sale/contracts/OverflowICO.sol
> +            finish();
Так onlyOwner если интернал дернуть, то этот модификатор не сработает, нет?

2023-09-10 22:01 UTC, valpaq commented on pkg/pre-sale/contracts/OverflowICO.sol
> +            finish();
добавил там тест последний на эту тему, не проходит из-за того что не запускаю финиш

2023-09-10 22:02 UTC, valpaq commented on pkg/pre-sale/contracts/OverflowICO.sol
> +        missedCommit[msg.sender] += _calculateCommit(amount);
0

2023-09-10 22:03 UTC, valpaq commented on pkg/pre-sale/contracts/OverflowICO.sol
> +        _updateTime();
при первом будет 0 в тайм ретио и всяких остальных, потому что он первый и ничего не потерял. а уже от него будет обновляться время и остальные будут меньше получать надбавку

2023-09-10 22:07 UTC, valpaq commented on pkg/pre-sale/contracts/OverflowICO.sol
> +        commitToken.safeTransfer(msg.sender, userCommit);
если даже на чуток будет меньше из-за ребейза, чем было изначально зафиксировано после финиша, то будет падать на недостатке, и тогда не все смогут заклеймить бонус, и достаточно на немного, как бы это контролировать

2023-09-10 22:08 UTC, valpaq commented on pkg/pre-sale/contracts/OverflowICO.sol
> +        commitToken.safeTransfer(msg.sender, userCommit);
к примеру изначально было 132000000, а стало после ребейза 131999000, то не все заберут, даже с этми округлениями, как бы это контролировать

2023-09-11 07:08 UTC, 4yuka requested changes

2023-09-11 10:05 UTC, venikpapa commented on pkg/pre-sale/contracts/OverflowICO.sol
>  contract OverflowICO is Ownable, LinearVesting {
Ярослав подготавливает доку

2023-09-11 10:06 UTC, venikpapa commented on pkg/pre-sale/contracts/Whitelist.sol
> +contract Whitelist {
Ярослав подготавливает доку

2023-09-11 10:06 UTC, venikpapa commented on pkg/pre-sale/contracts/WhitelistNFT.sol
> +contract WhitelistNFT is Initializable, ERC721Upgradeable, ERC721EnumerableUpgradeable, OwnableUpgradeable, UUPSUpgradeable {
Ярослав подготавливает доку

2023-09-11 10:07 UTC, venikpapa commented on pkg/pre-sale/contracts/example/LinearVestingExample.sol
удалил теперь точно)

2023-09-11 10:07 UTC, valpaq commented on pkg/pre-sale/contracts/OverflowICO.sol
> +        if (totalCommitments >= hardCap) {
мы берем после transfer и сравниваем тоталКоммитментс с хардкапом, но это же из-за ребейза, а значит сравнивать с хардкапом неправильно. Я бы totalCommitToBonus получение баланса взял бы перед трансфером и сравнивал его уже с тоталКоммитментс

2023-09-11 10:09 UTC, venikpapa commented on pkg/pre-sale/contracts/OverflowICO.sol
> +            uint256 elapsed = Math.min(block.timestamp, endTime) - Math.max(Math.min(lastUpdate, endTime), startTime);
уже нет этого метода

2023-09-11 10:16 UTC, venikpapa commented on pkg/pre-sale/contracts/OverflowICO.sol
> +        commitToken.safeTransfer(msg.sender, userCommit);
решили, что докинем если что, там не должно быть много

2023-09-11 10:16 UTC, venikpapa commented on pkg/pre-sale/contracts/OverflowICO.sol
> +            finish();
done

2023-09-11 10:19 UTC, venikpapa commented on pkg/pre-sale/contracts/OverflowICO.sol
> +        salesToken.safeTransfer(addr, delta);
да

2023-09-11 10:21 UTC, venikpapa commented on pkg/pre-sale/contracts/OverflowICO.sol
> +            if (block.timestamp < vestingBeginTime) {
done

2023-09-11 10:21 UTC, venikpapa commented on pkg/pre-sale/contracts/OverflowICO.sol
> +        if (block.timestamp < vestingBeginTime) {
done

2023-09-11 10:26 UTC, venikpapa commented on pkg/pre-sale/contracts/OverflowICO.sol
> +                uint256 userShare = commitments[user] * timeRatioStatic - missedCommit[user];
удалена эта переменная

2023-09-11 10:26 UTC, venikpapa commented on pkg/pre-sale/contracts/OverflowICO.sol
> +    function _updateTimeStatic() internal view returns (uint256) {
удален этот метод

2023-09-11 10:27 UTC, venikpapa commented on pkg/pre-sale/contracts/Whitelist.sol
> +contract Whitelist is IWhitelist, Initializable, AccessControlUpgradeable, UUPSUpgradeable {
Ярослав добавляет доки

2023-09-11 10:27 UTC, venikpapa commented on pkg/pre-sale/contracts/OverflowICO.sol
> +        totalTime = 1e18;
пременная удалена

2023-09-11 10:28 UTC, venikpapa commented on pkg/pre-sale/contracts/OverflowICO.sol
> +        return value * timeRatio / 1e18;
метод удален

2023-09-11 10:38 UTC, venikpapa commented on pkg/pre-sale/contracts/OverflowICO.sol
> +        totalSales = params.totalSales;
для гибкости контракта)

2023-09-11 10:39 UTC, venikpapa commented on pkg/pre-sale/contracts/OverflowICO.sol
> +            timeRatio += share * 1e18 / totalCommitments;
удалено это место

2023-09-11 10:40 UTC, venikpapa commented on pkg/pre-sale/contracts/OverflowICO.sol
> +                uint256 commitToSpend = Math.min(commitments[user], (commitments[user] * hardCap) / totalCommitments);
А как тут может получится отрицательное значение?

2023-09-11 10:55 UTC, venikpapa commented on pkg/pre-sale/contracts/OverflowICO.sol
> +        salesPerCommit = params.totalSales * 1e6 / params.hardCap;
done

2023-09-11 14:09 UTC, 4yuka approved these changes

2023-09-11 15:18 UTC, merged