inchSwapper
ovnstable/ovnstable-core pull request #255
Opened 2023-09-25 12:43 UTC by valpaq

2023-09-25 12:59 UTC, 4yuka requested changes
Нет тестов

2023-09-25 13:56 UTC, Vorh commented on pkg/core/contracts/InchSwapper.sol
> +    function swap(address recipient, address tokenIn, address tokenOut, uint256 amountIn, uint256 amountMinOut) public {
Метод должен быть защищен от сторонних вызовов

2023-09-25 13:56 UTC, Vorh commented on pkg/core/contracts/InchSwapper.sol
> +    uint256[50] private __gap;
Gap не нужен

2023-09-25 13:56 UTC, Vorh commented on pkg/core/contracts/InchSwapper.sol
> +    function initialize() public initializer {
Нужны тесты на каждую функцию

2023-09-26 10:31 UTC, 4yuka requested changes

2023-09-26 10:31 UTC, 4yuka commented on pkg/core/contracts/InchSwapper.sol
> +import "hardhat/console.sol";
удалить

2023-09-26 10:31 UTC, 4yuka commented on pkg/core/contracts/InchSwapper.sol
> +    mapping(address => mapping(address => Route)) public routePathsMap;
будем закрывать для внешних глаз пути обмена?

2023-09-26 10:31 UTC, 4yuka commented on pkg/core/deploy/core/29_setting_inch_swapper.js
> +        inchRouter = BASE.inchRouterV5;
сделай через DEFAULT.inchRouterV5, тогда не надо проверять сеть

2023-09-26 10:31 UTC, 4yuka commented on pkg/core/scripts/inchSwapperTest.js
> +    // console.log(`GrantRole: UNIT_ROLE to ${wallet.address}`);
удалить, если не нужно

2023-09-26 10:31 UTC, 4yuka commented on pkg/core/test/inchSwapper.js
если это тест для Base, то переименуй файл

2023-09-26 10:31 UTC, 4yuka commented on pkg/core/test/inchSwapper.js
> +    describe('add and swap and add and swap', () => {
непонятный describe

2023-09-26 10:31 UTC, 4yuka commented on pkg/core/test/inchSwapper.js
> +describe("InchSwapper", function () {
нет тестов на require проверки в контракте

2023-09-26 10:37 UTC, valpaq commented on pkg/core/test/inchSwapper.js
> +        it("diff user, smaller amount", async function () {
добавляем и проверяем от стандартного юзера, не от testAccount

2023-09-26 11:20 UTC, 4yuka requested changes

2023-09-26 11:20 UTC, 4yuka commented on pkg/core/contracts/InchSwapper.sol
> +            updateBlock: block.number,
blockNumber?

2023-09-26 11:20 UTC, 4yuka commented on pkg/core/contracts/InchSwapper.sol
> +        return routePathsMap[tokenIn][tokenOut];
что вернётся, если не будет в мапе? добавь тест на этот случай

2023-09-26 11:20 UTC, 4yuka commented on pkg/core/test/inchSwapperBase.js
> +    describe('check requires', () => {
можно объединить с предыдущим, чтобы код не дублировать

2023-09-26 12:39 UTC, merged