Strategy with inch
ovnstable/ovnstable-core pull request #258
Opened 2023-09-27 12:14 UTC by valpaq

2023-09-27 12:49 UTC, 4yuka requested changes

2023-09-27 12:49 UTC, 4yuka commented on pkg/strategies/arbitrum/contracts/StrategyEtsWithInchSwapper.sol
> +    uint256 swapSlippageBp;
Удалить. Уже есть параметр в Strategy

2023-09-27 12:49 UTC, 4yuka commented on pkg/strategies/arbitrum/contracts/StrategyEtsWithInchSwapper.sol
> +        asset.approve(address(inchSwapper), _amount);
хоть какие-то логические отступы сделай. плюс оставь комментарии. трудно читать код

2023-09-27 12:49 UTC, 4yuka commented on pkg/strategies/arbitrum/deploy/38_smm_alpha.js
> +        inchSwapper: "0x49398b8886d7708cF4BFDd305C4D622963d80F3d",
вынести в assets

2023-09-27 12:49 UTC, 4yuka commented on pkg/strategies/arbitrum/contracts/StrategyEtsWithInchSwapper.sol
> +contract StrategyEtsWithInch is Strategy {
Переименуй в StrategyEtsInch и файл тоже

2023-09-27 12:49 UTC, 4yuka commented on pkg/strategies/arbitrum/contracts/StrategyEtsWithInchSwapper.sol
> +        underlyingAsset.approve(address(hedgeExchanger), underlyingBalanceNow - underlyingBalanceWas);
Зачем эти вычисления делаешь? Для тестов это ок, но для вкладывания нам нужно под 0 всё класть

2023-09-27 12:49 UTC, 4yuka commented on pkg/strategies/arbitrum/contracts/StrategyEtsWithInchSwapper.sol
> +        hedgeExchanger.redeem(_amount);
Ты какой из токенов вытаскиваешь? Тут разве не нужна конвертация через ораклы?

2023-09-27 12:49 UTC, 4yuka commented on pkg/strategies/arbitrum/deploy/38_smm_alpha.js
> +        rebaseToken: rebaseToken,
отсортируй параметры в приоритете. Вначале hedge и rebase, потом всё остальное

2023-09-27 12:49 UTC, 4yuka commented on pkg/strategies/arbitrum/contracts/StrategyEtsWithInchSwapper.sol
> +    IERC20 public asset;
отсортируй параметры в приоритете. Вначале hedge и rebase, потом всё остальное

2023-09-27 12:49 UTC, 4yuka commented on pkg/strategies/arbitrum/contracts/StrategyEtsWithInchSwapper.sol
> +        address asset;
отсортируй параметры в приоритете. Вначале hedge и rebase, потом всё остальное

2023-09-27 12:49 UTC, 4yuka commented on pkg/strategies/arbitrum/contracts/StrategyEtsWithInchSwapper.sol
> +        asset = IERC20(params.asset);
отсортируй параметры в приоритете. Вначале hedge и rebase, потом всё остальное

2023-09-27 13:11 UTC, valpaq commented on pkg/strategies/arbitrum/contracts/StrategyEtsWithInchSwapper.sol
> +        hedgeExchanger.redeem(_amount);
вытаскиваю underlying и конвертирую в asset

2023-09-27 15:38 UTC, Vorh commented on pkg/common/utils/strategy-test.js
> +        // },
Надо расскоментить

2023-09-27 15:38 UTC, Vorh commented on pkg/common/utils/tests.js
> +async function impersonatingEtsGrantRoleWithInchSwapper(hedgeExchangerAddress, devjunAddress, strategyAddress, ownerAddress, inchSwapperAddress, asset, underlyingAsset, amountInMax0, amountInMax1) {
Что еще за devJun адрес? 
Это либо Timelock должен быть либо DEV либо Admin.

2023-09-27 15:38 UTC, Vorh commented on pkg/strategies/arbitrum/contracts/StrategyEtsInch.sol
> +        hedgeExchanger.redeem(_amount);
rebaseToken может иметь отличные decimals от asset и другую стоимость.

rebaseToken = DAI 
asset= USDC

Надо рассчитывать значение для метода redeem исходя из oracle и slippage при обмене.
Мы же всегда так делали в стратегии.

2023-09-27 15:38 UTC, Vorh commented on pkg/strategies/arbitrum/contracts/StrategyEtsInch.sol
> +        return asset.balanceOf(address(this)) + rebaseToken.balanceOf(address(this));
Здесь нужно rebaseToken переводить в asset через oracle

2023-09-27 15:39 UTC, Vorh commented
Конфликты нужно разрешить с мастером.

2023-09-28 05:13 UTC, 4yuka requested changes

2023-09-28 05:13 UTC, 4yuka commented on pkg/strategies/arbitrum/contracts/StrategyEtsInch.sol
> +        swapSlippageBP = 40;
Зачем до 40 увеличиваешь?

2023-09-28 05:13 UTC, 4yuka commented on pkg/strategies/arbitrum/contracts/StrategyEtsInch.sol
> +    function setParams(StrategyParams calldata params) external onlyAdmin {
Добавь проверки на пустые адреса

2023-09-28 05:13 UTC, 4yuka commented on pkg/strategies/arbitrum/contracts/StrategyEtsInch.sol
> +    // convert asset to underlying and then buy
комментарии оставь внутри функции перед каждым логическим блоком

2023-09-28 05:13 UTC, 4yuka commented on pkg/strategies/arbitrum/contracts/StrategyEtsInch.sol
> +    // get underlying, convert to asset
комментарии оставь внутри функции перед каждым логическим блоком

2023-09-28 05:13 UTC, 4yuka commented on pkg/strategies/arbitrum/contracts/StrategyEtsInch.sol
> +    // get all underlying, convert to asset
комментарии оставь внутри функции перед каждым логическим блоком

2023-09-28 05:13 UTC, 4yuka commented on pkg/strategies/arbitrum/contracts/StrategyEtsInch.sol
> +        uint256 amountToRedeem = _oracleAssetToUnderlying(_amount);
Нужно докидывать немного, чтобы не было ошибки. Расхождение может быть во-первых из-за оракла, а во-вторых слиппадж при свапе. Докидывай stakeSlippageBP

2023-09-28 05:13 UTC, 4yuka commented on pkg/strategies/arbitrum/deploy/38_smm_alpha.js
> +let rebaseToken = '0x13753271531cEF0AeF75db66035519Eb8dC95740';
можешь перенести в getParams

2023-09-28 05:13 UTC, 4yuka commented on pkg/strategies/arbitrum/test/main.js
> +        enabledReward: false,
не меняй общий тестовый файл. верни true

2023-09-28 07:19 UTC, valpaq commented on pkg/strategies/arbitrum/contracts/StrategyEtsInch.sol
> +        swapSlippageBP = 40;
не проходит на 20 при больших разницах в объеме
типа 1 млн у нас лежит в инч свапере и мы хотим обменять 1к, тогда упадет по слипаджу

2023-09-28 08:28 UTC, 4yuka commented on pkg/strategies/arbitrum/contracts/StrategyEtsInch.sol
> +        swapSlippageBP = 40;
Просто мы в целом и 20 бп не готовы терять из-за слиппаджа)

2023-09-28 15:51 UTC, merged