fund
ovnstable/ovnstable-core pull request #375
Opened 2024-08-15 17:45 UTC by montyp0x

2024-09-13 14:15 UTC, chpotl commented on pkg/fund/contracts/RoleManager.sol
> +        _grantRole(UNIT_ROLE, 0xab918d486c61ADd7c577F1af938117bBD422f088); // Dev
одна роль два раза выдается

2024-09-13 14:15 UTC, chpotl commented on pkg/fund/contracts/RoleManager.sol
> +        _grantRole(UNIT_ROLE, 0xab918d486c61ADd7c577F1af938117bBD422f088); // Dev
И не очень понятно что за кошелек это
мб его в переменную запихнуть или к константы

2024-09-13 14:15 UTC, chpotl commented on pkg/fund/contracts/RoleManager.sol
> +        _grantRole(UNIT_ROLE, 0xab918d486c61ADd7c577F1af938117bBD422f088); // Dev
наш дев сейчас 0x086dFe298907DFf27BD593BD85208D57e0155c94

2024-09-13 14:15 UTC, chpotl commented on pkg/fund/contracts/RoleManager.sol
> +        _grantRole(PORTFOLIO_AGENT_ROLE, 0xab918d486c61ADd7c577F1af938117bBD422f088); // Dev
тут тоже не очень понятно

2024-09-16 16:43 UTC, venikpapa commented on pkg/fund/contracts/RoleManager.sol
> +        _grantRole(UNIT_ROLE, 0xab918d486c61ADd7c577F1af938117bBD422f088); // Dev
РольМенеджер надо дропнуть вобще этот, он у нас один на чейн

2024-09-16 16:44 UTC, venikpapa commented on pkg/fund/contracts/Strategy.sol
> +// SPDX-License-Identifier: MIT
Код этого файла навероне неотличается от его первоначального вида, подумай чтобы тоже его дропнуть

2024-09-16 16:48 UTC, venikpapa commented on pkg/fund/contracts/FundExchange.sol
> +    function deposit(address _asset, uint256 _amount) external whenNotPaused nonReentrant onlyAdmin { // for depositor
Для депозитора создай отдельную роль, а то сейчас везде админ и это означает что таймлок. А надо кошель Макса любой какой он захочет, что есть чтобы через гаверненс этот депозитор кошель настраивался

2024-09-16 16:51 UTC, venikpapa commented on pkg/fund/contracts/Strategy.sol
> +import "@openzeppelin/contracts-upgradeable/access/AccessControlUpgradeable.sol";
А ты саму стратегию не писал по вкладыванию в usd+? Если писал, то не могу найти чтото

2024-09-16 16:52 UTC, venikpapa commented on pkg/fund/contracts/OvnFund.sol
> +// SPDX-License-Identifier: MIT
Надо договориться с Максом как токен будет называться. Напиши плз в чате где-нибудь. Это не так важно, но решить должны.

2024-09-16 19:30 UTC, chpotl commented on pkg/fund/contracts/OvnFund.sol
> +        _afterTokenTransfer(address(0), _to, 1);
Тут получается, что ты при любом трансфере минтишь и не убираешь из овнеров

2024-09-16 19:34 UTC, chpotl commented on pkg/fund/contracts/OvnFund.sol
> +        // emit Approval(msg.sender, _spender, _allowances[msg.sender][_spender]);
Мы в юсд+ эмитим это

2024-09-16 21:48 UTC, rbkn99 requested changes

2024-09-16 21:48 UTC, rbkn99 commented on pkg/fund/contracts/FundExchange.sol
> +        address asset;   // USDC | BUSD depends at chain
если может не только usdc быть, то нужно переименовать переменную выше

2024-09-16 21:48 UTC, rbkn99 commented on pkg/fund/contracts/FundExchange.sol
> +    function withdrawDeposit(address _asset, uint256 _amount) external whenNotPaused nonReentrant onlyAdmin returns (uint256) { // for depositor
нельзя логику с `_withdraw` объединить?

2024-09-16 21:48 UTC, rbkn99 commented on pkg/fund/contracts/FundExchange.sol
> +    function _requireOncePerBlock(bool isBalanced) internal {
мб такие методы которые используются в нескольких местах в проекте, вынести в connectors в либу?

2024-09-16 21:48 UTC, rbkn99 commented on pkg/fund/contracts/FundExchange.sol
> +    function getAvailabilityInfo() external view returns(uint256 _available, bool _paused, bool _deprecated) {
где устанавливается `_deprecated` ?

2024-09-16 21:48 UTC, rbkn99 commented on pkg/fund/contracts/OvnFund.sol
> +    modifier onlyExchanger() {
вынести в отдельный файл с ролями мб? как в даймонде сделано

2024-09-16 21:48 UTC, rbkn99 commented on pkg/fund/contracts/OvnFund.sol
> +        if (amount > MAX_SUPPLY / 10 ** 45) {
почему 10^45?

2024-09-16 21:48 UTC, rbkn99 commented on pkg/fund/contracts/libraries/StableMath.sol
> +pragma solidity ^0.8.0;
эту либу точно можно вынести из фонда

2024-09-16 21:48 UTC, rbkn99 commented on pkg/fund/contracts/libraries/WadRayMath.sol
> +/**
аналогично

2024-09-16 21:48 UTC, rbkn99 commented on pkg/fund/deploy/ovn_fund.js
> +    let params = { args: ["OVN+", "OVN+", 6] };
symbol != name, как выберем название нужно поправить

2024-09-16 21:48 UTC, rbkn99 commented on pkg/fund/test/shares_test.js
> +        let amounts = ['100000000000', '10000000000', '1000000000', '100000000', '10000000', '1000000', '100000', '10000', '1000', '100', '10', '1'];
вынести из тест кейсов

2024-09-17 13:18 UTC, rbkn99 requested changes

2024-09-17 13:18 UTC, rbkn99 commented on pkg/fund/contracts/FundExchange.sol
> +            delta = totalNav * LIQ_DELTA_DM / (ovnPlus.totalSupply() + totalDeposit);
а зачем здесь `delta` если она дальше нигде не юзается?

2024-09-17 13:18 UTC, rbkn99 commented on pkg/fund/contracts/FundExchange.sol
> +        totalNav = _assetToRebase(portfolioManager.totalNetAssets());
где мог поменяться `totalNav`?

2024-09-17 13:18 UTC, rbkn99 commented on pkg/fund/contracts/FundExchange.sol
> +        require(totalNav >= totalOvnPlus, 'negative rebase');
этот `require` не выполнится никогда по идее

2024-09-19 11:17 UTC, venikpapa commented on pkg/fund/contracts/FundExchange.sol
> +    function _requireOncePerBlock(bool isBalanced) internal {
Не, давайте пока не будем

2024-09-19 15:25 UTC, montyp0x commented on pkg/fund/contracts/FundExchange.sol
> +    IERC20 public usdc; // asset name
да

2024-09-19 15:27 UTC, montyp0x commented on pkg/fund/contracts/OvnFund.sol
> +        uint256 creditsDeducted = assetToCredit(_value);
done

2024-09-19 15:28 UTC, montyp0x commented on pkg/fund/contracts/RoleManager.sol
> +        _grantRole(UNIT_ROLE, 0xab918d486c61ADd7c577F1af938117bBD422f088); // Dev
done

2024-09-19 15:32 UTC, montyp0x commented on .gitignore
> +pkg/core/deployments/
ну я когда удалял кор папку, хотел ее не пушить на гит

done

2024-09-19 15:34 UTC, montyp0x commented on pkg/fund/contracts/FundExchange.sol
> +        address asset;   // USDC | BUSD depends at chain
done

2024-09-19 15:39 UTC, montyp0x commented on pkg/fund/contracts/OvnFund.sol
> +        _afterTokenTransfer(address(0), _to, 1);
потому что мы проходимся по списку оунеров, когда минтим shareholder'ам 
то есть если у человека нет сейчас токенов, то он все равно должен быть в оунерах

пон?

2024-09-19 15:52 UTC, montyp0x commented on pkg/fund/contracts/FundExchange.sol
> +    function getAvailabilityInfo() external view returns(uint256 _available, bool _paused, bool _deprecated) {
этот метод нам не нужен вообще, спс

2024-09-19 15:53 UTC, montyp0x commented on pkg/fund/test/shares_test.js
> +        let amounts = ['100000000000', '10000000000', '1000000000', '100000000', '10000000', '1000000', '100000', '10000', '1000', '100', '10', '1'];
почему

2024-09-19 17:29 UTC, chpotl commented on pkg/fund/contracts/OvnFund.sol
> +        // emit Approval(msg.sender, _spender, _allowances[msg.sender][_spender]);
да
френдли ремаиндер

2024-09-19 18:23 UTC, montyp0x commented on pkg/fund/contracts/FundExchange.sol
> +        require(totalNav >= totalOvnPlus, 'negative rebase');
done

2024-09-19 18:51 UTC, montyp0x commented on pkg/fund/contracts/FundExchange.sol
> +        totalNav = _assetToRebase(portfolioManager.totalNetAssets());
done

2024-09-19 18:51 UTC, montyp0x commented on pkg/fund/contracts/FundExchange.sol
> +            delta = totalNav * LIQ_DELTA_DM / (ovnPlus.totalSupply() + totalDeposit);
done

2024-09-19 19:00 UTC, montyp0x commented on pkg/fund/deploy/ovn_fund.js
> +    let params = { args: ["OVN+", "OVN+", 6] };
done

2024-09-20 09:07 UTC, montyp0x commented on pkg/common/utils/script-utils.js
> +    console.log("amount: ", amount);
done

2024-09-20 09:07 UTC, montyp0x commented on pkg/fund/contracts/Strategy.sol
> +// SPDX-License-Identifier: MIT
done

2024-09-24 09:51 UTC, venikpapa requested changes

2024-09-24 09:51 UTC, venikpapa commented on pkg/fund/contracts/FundExchange.sol
> +        uint256 expectedTotalFund = totalFund + profit;
Я моргу написать

uint256 profit = totalNav - totalFund;
uint256 expectedTotalFund = totalNav;

Если это одно и то же, то два последующих рекваера это прям одно и то же же.

2024-09-24 09:51 UTC, venikpapa commented on pkg/fund/contracts/MotivationalFund.sol
> +        _totalShares -= _amount;
надо бы тут рекваер поставить, что у чела вобще есть столько шейрсов сколько мы хотим у него убрать

2024-09-24 09:51 UTC, venikpapa commented on pkg/fund/contracts/MotivationalFund.sol
> +    function changeNegativeSupply(uint256 _newTotalSupply)
Не совсем понимаю по changeNegativeSupply. Тут мы пропорционально у всех немного отнимаем, а в Эксчендже мы отничаем только у депозитора баланс. Я чето навероне не понял

2024-09-24 09:51 UTC, venikpapa commented on pkg/fund/contracts/MotivationalFund.sol
> +            if (balanceOf(from) == 0 && sharesBalanceOf(from) == 0) {
У меня ошибка при компиляции с sharesBalanceOf. Глянь плз

2024-09-24 09:51 UTC, venikpapa commented on pkg/fund/contracts/MotivationalFund.sol
> +            if (balanceOf(from) == 0 && sharesBalanceOf(from) == 0) {
И можешь про эту добавку поподробнее рассказать. Когда могут быть следуюшие кейсы:
1. (balanceOf(from) == 0 && sharesBalanceOf(from) == 0)
2. (balanceOf(from) != 0 && sharesBalanceOf(from) == 0)
3. (balanceOf(from) == 0 && sharesBalanceOf(from) != 0)
4. (balanceOf(from) != 0 && sharesBalanceOf(from) != 0)

Все ли они могут быть этот чтото тут может быть избыточным?

2024-09-24 09:52 UTC, venikpapa commented on pkg/fund/contracts/MotivationalFund.sol
> +            if (balanceOf(from) == 0 && sharesBalanceOf(from) == 0) {
И общий коммент по поводу форматирования: в некоторых бы местах я бы это в одну строку сделал. Глянь плз где тебе глаз режет там поправь влз, но это так, просто моя хотелка так как я к определенному стилю уже привык

2024-09-24 13:06 UTC, montyp0x commented on pkg/fund/contracts/MotivationalFund.sol
> +        _totalShares -= _amount;
done

2024-09-24 13:07 UTC, montyp0x commented on pkg/fund/contracts/MotivationalFund.sol
> +            if (balanceOf(from) == 0 && sharesBalanceOf(from) == 0) {
done

2024-09-24 13:08 UTC, montyp0x commented on pkg/fund/contracts/MotivationalFund.sol
> +    function changeNegativeSupply(uint256 _newTotalSupply)
в контракте фонда мы уменьшаем у челов их кредиты, а в exchange мы вычитаем долю депозитора

2024-09-24 13:16 UTC, montyp0x commented on pkg/fund/contracts/FundExchange.sol
> +        uint256 expectedTotalFund = totalFund + profit;
да, спасибо!

2024-09-25 07:54 UTC, venikpapa commented on pkg/fund/contracts/MotivationalFund.sol
> +    function changeNegativeSupply(uint256 _newTotalSupply)
А это ок? Просто странно ведь когда это вычитается из двух разных мест, не?

2024-09-25 07:56 UTC, venikpapa commented
И тут конфликты при мерже

2024-09-25 07:57 UTC, venikpapa commented on pkg/fund/contracts/MotivationalFund.sol
> +            if (balanceOf(from) == 0 && sharesBalanceOf(from) == 0) {
Тут тоже давай поговорим про это

2024-10-09 05:35 UTC, merged