odos fix
ovnstable/ovnstable-core pull request #377
Opened 2024-08-27 23:07 UTC by rbkn99

2024-09-20 14:17 UTC, venikpapa requested changes

2024-09-20 14:19 UTC, venikpapa commented
И вообще общий комментарий: все те котнракты, которые будут общими, а не конкретно содержащие логиу Аэродрома, Пэнкейка и тд. Должны настолько быть унифицированы, чтобы подходили и к Univ2, если это невозможно значит модобные фасеты должны быть названы ***V3.sol подразуменвя, что для v2 оди будут прям по-другому переписаны.

2024-09-20 16:45 UTC, montyp0x commented on pkg/zap/contracts/facets/core/ProportionFacet.sol
вынести инит IMasterFacet

2024-09-23 08:25 UTC, venikpapa commented on pkg/zap/contracts/facets/aggregator/PancakeAggregatorFacet.sol
> +        return IMasterChefV3(LibCoreStorage.coreStorage().masterChefV3).poolLength() - 1;
А почему тут -1?

2024-09-24 16:25 UTC, rbkn99 commented on pkg/zap/contracts/facets/aggregator/AerodromeAggregatorFacet.sol
> -contract PoolFetcherAerodromeFacet is IPoolFetcherFacet {
обсуждали с Леней сегодня, довольно много кода унифицировать придется, нужно тщательно оценить сперва

2024-09-24 16:36 UTC, rbkn99 commented on pkg/zap/contracts/facets/core/ProportionFacet.sol
>          token0Amount = token0Amount * (denominator / dec0);
у нас `amounts` в `getLiquidity` передаются как произвольные числа в пропорции децималс. как получили - делим обратно

2024-09-24 16:36 UTC, rbkn99 commented on pkg/zap/contracts/facets/aggregator/PancakeAggregatorFacet.sol
> +        return IMasterChefV3(LibCoreStorage.coreStorage().masterChefV3).poolLength() - 1;
0 пул в панкейке - это address(0)

2024-09-24 19:01 UTC, merged