morpho claim
ovnstable/ovnstable-core pull request #379
Opened 2024-09-04 00:39 UTC by montyp0x

2024-09-10 10:15 UTC, chpotl commented on pkg/strategies/base/contracts/StrategyMorpho.sol
> +        bundler.multicall(data);
А чисто в теории можно в мульткол передать дату, которая выведет деньги со стратегии?
Просто мне Никита, говорил, что не очень хорошо давать такие большие возможности методу?

2024-09-11 04:17 UTC, montyp0x commented on pkg/strategies/base/contracts/StrategyMorpho.sol
> +        bundler.multicall(data);
ну только если взломают бандлер и поменяют там мультиколл, но даже так от нашего мультиколла хуже не будет, мы и так тогда потеряем доступ к вложенным деньгам. 
кроме того, _claimRewards может вызвать только PM, так что шансы на потери кратно уменьшаются

2024-09-11 08:04 UTC, chpotl commented on pkg/strategies/base/contracts/StrategyMorpho.sol
> +        bundler.multicall(data);
окей тогда LGTM

2024-09-11 08:09 UTC, chpotl approved these changes

2024-09-11 10:03 UTC, rbkn99 requested changes

2024-09-11 10:03 UTC, rbkn99 commented on pkg/common/utils/deployProxy.js
> +            impl = await upgrades.upgradeProxy(proxy, contractFactory, { unsafeAllow: unsafeAllow, redeployImplementation: always });
я бы сделал это параметром со значением `always` по дефолту

2024-09-12 04:44 UTC, montyp0x commented on pkg/strategies/base/contracts/StrategyMorpho.sol
> +        address chainAgnosticBundler = address(0x23055618898e202386e6c13955a58D3C68200BFB);
зачем

2024-09-12 04:44 UTC, montyp0x commented on pkg/proposals/scripts/base/40_add_morpho_rewards.js
> +    let dataAlpha = ["0x6b89026a0000000000000000000000009e3380f8b29e8f85ca19effa80fb41149417d9430000000000000000000000002e99704871c726893c94bbe7e5ba4c2bed976a86000000000000000000000000a88594d40472762
из симуляции рабби

2024-09-12 08:48 UTC, rbkn99 commented on pkg/strategies/base/contracts/StrategyMorpho.sol
> +        address chainAgnosticBundler = address(0x23055618898e202386e6c13955a58D3C68200BFB);
чтобы более структурированно было. но вообще up to you, можно и так оставить

2024-09-12 11:16 UTC, venikpapa requested changes

2024-09-12 11:16 UTC, venikpapa commented on pkg/common/utils/deployProxy.js
> +            impl = await upgrades.upgradeProxy(proxy, contractFactory, { unsafeAllow: unsafeAllow, redeployImplementation: always });
А зачем ее вобще всегда передеплоивать? Заем нам этот флаг?

2024-09-12 11:16 UTC, venikpapa commented on pkg/common/utils/deployProxy.js
> +                redeployImplementation: "always"
same

2024-09-12 11:16 UTC, venikpapa commented on pkg/proposals/scripts/base/40_add_morpho_rewards.js
> +    function getParamsAlpha() {
ты вроде как можешь заинджектить эти параметры из деплой скрипта этой стратегии, но это не обязательно, просто знай что так можно делать и не дублировать код

2024-09-12 11:16 UTC, venikpapa commented on pkg/strategies/base/contracts/StrategyMorpho.sol
> +    function _claimRewards(address _beneficiary, bytes[] memory data) public onlyPortfolioAgent {
Так делать нельзя. _claimRewards интернал функция, она дергается в контракте стратегии, посмотри пожалуйста. Это означает что изменив ее ежедневный клей мроходить не будет, потому что методы не совпадают. Поэтому тебе тот метод надо будет оставить с такой же шапкой и добавить еще один метод именно для ручного дерганья. В него уже будет передаваться data.

2024-09-12 11:16 UTC, venikpapa commented on pkg/strategies/base/contracts/StrategyMorpho.sol
> +        address chainAgnosticBundler = address(0x23055618898e202386e6c13955a58D3C68200BFB);
Адрес вынеси в параметр, чтобы можно его было сеттить вместе с остальными и добавь его в ассетс. Если он поменяется кравильнее будет не передеплаивать код, а пересеттить просто параметр и все. Все адреса стараемся заносить в assets и тянуть оттуда

2024-09-12 11:16 UTC, venikpapa commented on pkg/strategies/base/deploy/22_strategy_morpho_alpha.js
> +        await deployProxyMulti(name, 'StrategyMorpho', deployments, save, null);
тут точно параметры верные у deployProxyMulti ты сделал? Также если поменял альфу, то и бетту надо менять же

2024-09-12 11:33 UTC, montyp0x commented on pkg/strategies/base/deploy/22_strategy_morpho_alpha.js
> +        await deployProxyMulti(name, 'StrategyMorpho', deployments, save, null);
бета изменена и так, параметры вроде верные, надо на что-то конкретное внимание обратить?

2024-09-12 11:35 UTC, montyp0x commented on pkg/common/utils/deployProxy.js
> +                redeployImplementation: "always"
если делать без этого флага, то изменения, которые не меняют абишку не деплоятся

2024-09-12 12:44 UTC, montyp0x commented on pkg/strategies/base/contracts/StrategyMorpho.sol
> +    function _claimRewards(address _beneficiary, bytes[] memory data) public onlyPortfolioAgent {
done

2024-09-12 12:44 UTC, montyp0x commented on pkg/proposals/scripts/base/40_add_morpho_rewards.js
> +    function getParamsAlpha() {
done

2024-09-12 14:59 UTC, venikpapa commented on pkg/common/utils/deployProxy.js
> +                redeployImplementation: "always"
Этот флаг должен иметь сделющий смысл: если байткод не меняется, то передеплоя не будет. Не про абишку это должно быть, иначе как бы мы вобще все деплоили у нас в проекте всегда без этого флага. Перепроверь плз этот впрос.

2024-09-12 15:00 UTC, venikpapa commented on pkg/strategies/base/contracts/StrategyMorpho.sol
> +    function _claimRewards(address _beneficiary, bytes[] memory data) public onlyPortfolioAgent {
а где я не вижу изменений)

2024-09-13 09:02 UTC, rbkn99 commented on pkg/common/utils/deployProxy.js
> +            impl = await upgrades.upgradeProxy(proxy, contractFactory, { unsafeAllow: unsafeAllow, redeployImplementation: always });
@venikpapa там прикол что если не поменялись сигнатуры методов, то хардхэт может не передеплоить почему-то. даже если байткод поменялся

2024-09-14 01:39 UTC, merged